base_url = "https://nic.dockerz.net"
compile_sass = true
title = "Nic Docker"
description = "I'm a designer and developer with a love for crafting engaging experiences."
generate_feed = true

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    {url = "/design", name = "DESIGN"},
    {url = "/games", name = "GAMES"},
    {url = "/blog", name = "BLOG"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "boron"
