theme = "hyde"

base_url = "https://zola-hyde.netlify.com"
compile_sass = true
title = "Nic Docker"
description = "Welcome to my site"
generate_feed = true

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    {url = "/", name = "Portfolio"},
    {url = "/", name = "Blog"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
