theme = "hyde"

base_url = "/some-article"
compile_sass = true
title = "NIC DOCKER"
description = "Welcome to my site"
generate_feed = true

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    {url = "/portfolio", name = "PORTFOLIO"},
    {url = "/blog", name = "BLOG"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
