theme = "hyde"

base_url = "https://nic.dockerz.net"
compile_sass = true
title = "Nic Docker"
description = "Game development and other experiments"
generate_feed = true

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    {url = "/games", name = "GAMES"},
    {url = "/art", name = "ART"},
    {url = "/blog", name = "BLOG"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
