base_url = "https://nic.dockerz.net"
compile_sass = true
title = "Nic Docker"
description = "Fueled by a love of creating, in any medium."
generate_feed = true

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    {url = "/games", name = "GAMES"},
    {url = "/design", name = "DESIGN"},
    {url = "/art", name = "SKETCHBOOK"},
    {url = "/blog", name = "BLOG"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "boron"
